workflows:
  ios-release:
    name: iOS Release
    environment:
      vars:
        XCODE_WORKSPACE: "Runner.xcworkspace"  # default for Flutter
        XCODE_SCHEME: "Runner"
      flutter: stable
      xcode: latest
      cocoapods: default

    cache:
      cache_paths:
        - ios/Pods/**                    
        - $HOME/.pub-cache/**             
        - $HOME/Library/Caches/CocoaPods/**  

    scripts:
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Install pods
        script: |
          find . -name "Podfile" -execdir pod install \;
      - name: Flutter analyze
        script: |
          flutter analyze
      - name: Flutter unit tests
        script: |
          flutter test
        ignore_failure: true
      - name: Flutter build iOS release (with IPA export)
        script: |
          flutter build ios --release --no-codesign   # Codemagic will codesign later

    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log