workflows:
  ios-release:
    name: iOS Release
    environment:
      flutter: stable
      xcode: latest
      cocoapods: defaul
    scripts:
      - name: Set up code signing settings on Xcode project
        script: |
          xcode-project use-profil
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Install pods
        script: |
          find . -name "Podfile" -execdir pod install \;
      - name: Flutter analyze
        script: |
          flutter analyze
      - name: Flutter unit tests
        script: |
          flutter test
        ignore_failure: true
      - name: Flutter build iOS release (with IPA export)
        script: |
          flutter clean
          flutter build ios --release --no-codesign   # Codemagic will codesign later

    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log