workflows:
  ios-release:
    name: iOS Release
    environment:
      vars:
        XCODE_WORKSPACE: "Runner.xcworkspace"  # default for Flutter
        XCODE_SCHEME: "Runner"
      flutter: stable
      xcode: latest
      cocoapods: default

    cache:
      key: v5-{{ checksum "pubspec.lock" }}-{{ checksum "ios/Podfile.lock" }}
      paths:
        - ios/Pods/**                    
        - $HOME/.pub-cache/**             
        - $HOME/Library/Caches/CocoaPods/**  

    scripts:
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Restore Pods
        script: |
          if [ -d "ios/Pods" ]; then
            echo "Pods already exist, skipping full pod install"
            cd ios && pod install
          else
            cd ios && pod install
          fi
      - name: Flutter analyze
        script: |
          flutter analyze
      - name: Flutter unit tests
        script: |
          flutter test
        ignore_failure: true
      - name: Flutter build iOS release (with IPA export)
        script: |
          flutter build ios --release --no-codesign   # Codemagic will codesign later

    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log